package ava.io.authentication_manager.utils.custom_excpeption;

//public class WrongOTPException extends RuntimeException{
//}
